apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: su5fjy0lh-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: su5fjy0lh-java-quarkus 
  name: su5fjy0lh-java-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: su5fjy0lh-java-quarkus 
